### ISSUE TITLE
在代码中配置了JdbcUsersConnectionRepository但是实际没有生效

### ISSUE THREAD

**Issue by Jayruiping** [jojozhai/security#3]
在SocialConfig中配置了JdbcUsersConnectionRepository,但是运行时SocialAuthenticationProvider中的UsersConnectionRepositor是InMemoryUsersConnectionRepository！

**Comment by Jayruiping** [comment]
toUserId()方法返回的一直是null

**Comment by xiaodaoM** [comment]
我也是.请问你解决了吗

**Comment by xiaodaoM** [comment]
hi

**Comment by longfeizheng** [comment]
把写在SocialConfig类中的getUsersConnectionRepository方法放置到QQAuthConfig中即可。

**Comment by Jayruiping** [comment]
@longfeizheng 感谢 解决了
